### ISSUE TITLE
Tabs rendered from dynamic array resulting tab sorts error

### ISSUE THREAD

**Issue by VancySavoki** [youzan/vant#1361]
**Describe the bug**
Tabs rendered from dynamic array results an unexpecting tab sorts error.whether if I use it on incorrect way?Thanks!

**Screenshots**
Add screenshots to help explain your problem.
as jsfiddle example

**Environment**
 - Device: PC
 - Browser:  chrome
 - Vant Version: 1.1.9

**Reproduce**
Provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle.
https://jsfiddle.net/dfarLdko/168/

**Comment by chenjiahan** [comment]
Will be fixed in next minor version

**Comment by chenjiahan** [comment]
Fixed in v1.1.11

**Comment by VancySavoki** [comment]
Hello，@chenjiahan，
When I tested with latest vant version, in this example https://jsfiddle.net/dfarLdko/168/,
it surely be fixed in some way, but still exists random sorting error, see http://jsfiddle.net/dfarLdko/210/.
Could you please help me?

**Comment by chenjiahan** [comment]
Fixed in v1.1.12
